package com.baoliang.Model;


import java.util.HashSet;
import java.util.Set;

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	/**
	 * 
	 */
	private String acnum;
	private String boss;
	private String phone;
	private String goods;
	private String start;
	private String destination;
	private String drivernum;
	private String lat;
	private String longt;
	private String latdes;
	private String longdes;
	private String receiver;
	private String recephone;
	public String getRecephone() {
		return recephone;
	}

	public void setRecephone(String recephone) {
		this.recephone = recephone;
	}

	public String getReceiver() {
		return receiver;
	}

	public void setReceiver(String receiver) {
		this.receiver = receiver;
	}

	public String getLat() {
		return lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public String getLongt() {
		return longt;
	}

	public void setLongt(String longt) {
		this.longt = longt;
	}

	public String getLatdes() {
		return latdes;
	}

	public void setLatdes(String latdes) {
		this.latdes = latdes;
	}

	public String getLongdes() {
		return longdes;
	}

	public void setLongdes(String longdes) {
		this.longdes = longdes;
	}

	public String getDrivernum() {
		return drivernum;
	}

	public void setDrivernum(String drivernum) {
		this.drivernum = drivernum;
	}

	public String getStatue() {
		return statue;
	}

	public void setStatue(String statue) {
		this.statue = statue;
	}

	public String getCar() {
		return car;
	}

	public void setCar(String car) {
		this.car = car;
	}

	public double getWeight() {
		return weight;
	}

	public void setWeight(double weight) {
		this.weight = weight;
	}

	private String statue;
	private String car;
	private double weight;
	

	public Application() {
	}

	public Application(String acnum) {
		this.acnum = acnum;
	}

	public Application(String acnum, String boss, String phone, String goods, String start, String destination,
			String drivernum,String statue,double weight,String car,String receiver,String recephone) {
		this.acnum = acnum;
		this.boss = boss;
		this.phone = phone;
		this.goods = goods;
		this.start = start;
		this.destination = destination;
		
		this.drivernum=drivernum;
		this.statue=statue;
		this.weight= weight;
		this.car=car;
		this.receiver=receiver;
		this.recephone=recephone;
	}

	public String getAcnum() {
		return this.acnum;
	}

	public void setAcnum(String acnum) {
		this.acnum = acnum;
	}

	public String getBoss() {
		return this.boss;
	}

	public void setBoss(String boss) {
		this.boss = boss;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getGoods() {
		return this.goods;
	}

	public void setGoods(String goods) {
		this.goods = goods;
	}

	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	
}
