// default package
// Generated 2018-1-5 11:37:21 by Hibernate Tools 5.2.6.Final
package com.baoliang.Model;
import java.util.HashSet;
import java.util.Set;

/**
 * Drivers generated by hbm2java
 */
public class Drivers implements java.io.Serializable {

	private String drivernums;
	private String name;
	private String phone;
	private String pass;
	private String carnum;
	private Double cargo;
	private String statue;
	private String sumlength;


	public Drivers() {
	}

	public Drivers(String drivernums) {
		this.drivernums = drivernums;
	}

	public Drivers(String drivernums, String name, String phone, String pass, String carnum, Double cargo,
			String statue, String sumlength, Set apses) {
		this.drivernums = drivernums;
		this.name = name;
		this.phone = phone;
		this.pass = pass;
		this.carnum = carnum;
		this.cargo = cargo;
		this.statue = statue;
		this.sumlength = sumlength;
		
	}

	public String getDrivernums() {
		return this.drivernums;
	}

	public void setDrivernums(String drivernums) {
		this.drivernums = drivernums;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getCarnum() {
		return this.carnum;
	}

	public void setCarnum(String carnum) {
		this.carnum = carnum;
	}

	public Double getCargo() {
		return this.cargo;
	}

	public void setCargo(Double cargo) {
		this.cargo = cargo;
	}

	public String getStatue() {
		return this.statue;
	}

	public void setStatue(String statue) {
		this.statue = statue;
	}

	public String getSumlength() {
		return this.sumlength;
	}

	public void setSumlength(String sumlength) {
		this.sumlength = sumlength;
	}

	

}
